
sudo: required

services:
  - docker

install:
  - wget https://storage.googleapis.com/involucro-1149.appspot.com/involucro
  - chmod u+x involucro
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: ./build.sh
