
sudo: required

services:
  - docker

install:
  - wget https://storage.googleapis.com/involucro-1149.appspot.com/involucro
  - chmod u+x involucro

script:
  - ./build-package.sh hello 2.10
  - ./build-package.sh base64 1.5
  - ./build-package.sh mtr 0.86

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push thriqon/mulled:hello
  - docker push thriqon/mulled:base64
  - docker push thriqon/mulled:mtr

