
sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - wget https://storage.googleapis.com/involucro-1149.appspot.com/involucro
  - chmod u+x involucro
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: ./build.sh

secure: "Hs3Y/Dw3lPCG5GsyDoTdEJmshuLNJUQBVQZcKFUAVZNiLhoFkKFdVV8H9Wkl9vZV1OFkhSNa1rgM5Ok+hfUCWw0fzS3pvFZ8e8tXmoNpoXZ2IUe5VfQy6uHrRHDiaicN0E9zMDZg48SggrraZLT4Hlc0yTCyQhz/IW0XlWMeWMqkt3QVG2ROvhl71f5WCltSgCvQSO9FQiHvfRE7RJiHbhmU81ylynKCsrUfdjio0VSmy8QO+yoIoQ8Y4TKMrSz3+Tyq2wvlTpJUkumQ50QUslsDdfVbQw+8QNW7iaop8MrHHZAiL613mGWSfaoOCA00R/NEpF0Wci7Jb9YYyCG6ncn05B7UU5eGR3thUSQz6MtTGq2ndD67wi63Tpcj+TssQtPwevX7xg/vpS5Rnr2xJMKBrCSjG3irjU7R/oHurKSuUYABk6ZyuhZAAgNw4T8nEX2pFfgRAkUXIC3VdlYmO/st6/njVkOKnb5Z+pTDIQczD+qFui8DKhSbi7S/a9nMiGuWZCqwQJTra+NL3b1I4RFB3PT3gMXCm3CJVYhJfgG8alOb4nWWTcGY2+U6QAmg5XOW93nWrchtlZ8NgpLahIlz+CWYZ4JzQJLZzVBkHvZ1NDYg/Qm8QDgvkisUvbgQp34vBCuH7UGOzYYsuKeZdHPHMkYXgC1/UOlAbMYumfk="
