
inv.task('build')
  .using('busybox')
    .run('mkdir', '-p', 'dist')
  .using('thriqon/linuxbrew-alpine')
    .withConfig({entrypoint = {"/bin/sh", "-c"}})
    .withHostConfig({binds = {"./dist:/root/brew/Cellar"}})
    .run('/root/brew/bin/brew install ' .. ENV.PKG .. ' && /root/brew/bin/brew test' .. ENV.PKG)
  .wrap('dist').inImage('mwcampbell/muslbase-runtime')
    .at("/cellar")
    .withConfig({entrypoint = {"/cellar/" .. ENV.PKG .. "/" .. ENV.VERS .. "/bin/" .. ENV.BIN}})
    .as('thriqon/mulled:' .. ENV.PKG)
  .using('busybox')
    .run('rm', '-rf', 'dist')
